name: GitHub-hosted action runners latency report

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Download gcping
        run: curl -s -o gcping https://storage.googleapis.com/gcping-release/gcping_linux_amd64_latest && chmod +x gcping

      - name: Measure latencies
        run: ./gcping -csv-cum > gcping.csv
        # region,latency_ns,errors

      - name: Generate summary
        run: |
          echo "## GitHub-hosted action runners latency report for Google Cloud Platform\n" >> $GITHUB_STEP_SUMMARY
          echo "|  Region  | Latency (ms) |" >> $GITHUB_STEP_SUMMARY
          echo "|:---------|-------------:|" >> $GITHUB_STEP_SUMMARY

          # Sort by latency and format as markdown table
          sort -t',' -k2 -n <(tail -n +2 gcping.csv) | awk -F',' '{printf "| `%s` | %.2f |\n", $1, $2/1000000}' >> $GITHUB_STEP_SUMMARY
